### ISSUE TITLE
Angular integration

### ISSUE THREAD

**Issue by SmailHammour** [Yoonit-Labs/nativescript-yoonit-camera#39]
Hello, 

Are you guys planning on integrating Angular?

**Comment by luiguild** [comment]
Hi @SmailHammour! We appreciated your interest to use Yoonit Camera in your Angular projects. Unfortunately, we do not have plans to port or integrate with Angular, because we don't currently work with him.

But we are not closed to receive a PR that integrate our project with Angular. We know that it's possible to use, because at the bottom, it's a pure NS plugin with a single file that's configure a Vue Plugin.

If you can send a PR making this, certainly we will work together to make this happen :)
